from fastapi import APIRouter

from backend.services.lap_service import LapServiceDep
from backend.schemas.driver_laps_schema import DriverLapsResponse

router = APIRouter()


@router.get("/laps/{session_key}/{driver_number}",
            response_model=DriverLapsResponse,
            summary="Gets a driver's session laps",
            description="Accesses the DB and retrives all laps a driver completed in a session, modelling the response using a schema."
                        "session_key is an Integer generated by OpenF1 to connect a session to everything that pertains it."
)
def read_driver_session_laps(session_key: int, driver_number: int, service: LapServiceDep):
    return service.get_driver_laps(session_key, driver_number)
