from fastapi import APIRouter

from backend.services.session_service import SessionServiceDep
from backend.schemas.session_schema import SessionResponse
from backend.schemas.read_session_result import SessionResultResponse

router = APIRouter()


@router.get("/sessions/{meeting_key}",
            response_model=list[SessionResponse],
            summary="Gets sessions",
            description="Accesses de DB and fetches all sessions that happened in a given event."
                        "meeting_key is an Integer generated by OpenF1 that connects a F1 to everything that pertains it."
)
def read_sessions(meeting_key: int, service: SessionServiceDep):
    return service.get_sessions(meeting_key)


@router.get("/session_result/{session_key}",
            response_model=SessionResultResponse)
def read_session_result(session_key: int, service: SessionServiceDep):
    return service.get_session_result(session_key)
