from fastapi import APIRouter

from backend.crud.lap import get_driver_lap_times
from backend.db.db_utils import SessionDep
from backend.constants import FALLBACK_COMPOUND
from backend.schemas.driver_laps_schema import DriverLapsRead, LapRead

router = APIRouter()

@router.get("/laps/{session_key}/{driver_number}",
            response_model=DriverLapsRead,
            summary="Gets a driver's session laps",
            description="Accesses the DB and retrives all laps a driver completed in a session, modelling the response using a schema."
                        "session_key is an Integer generated by OpenF1 to connect a session to everything that pertains it."
)
def read_driver_session_laps(session:SessionDep, session_key:int, driver_number:int):
    driver, session_data ,laps = get_driver_lap_times(session, session_key, driver_number)

    driver_laps = DriverLapsRead(
        driver_number=session_data.driver_number,
        first_name=driver.first_name,
        last_name=driver.last_name,
        team=session_data.team,
        headshot_url=driver.headshot_url,
        laps = [
            LapRead(
                lap_number=lap.lap_number or 0,
                time = lap.lap_time or 0.0,
                speed_trap= lap.st_speed or 0,
                is_pit_out_lap=lap.is_pit_out_lap or False,
                compound=lap.compound or FALLBACK_COMPOUND
            )
            for lap in laps
        ]
    )
    return driver_laps
